// This file is generated by npm run build:icons

export type IconName =
	| "lucide/activity"
	| "lucide/alarm-plus"
	| "lucide/alert-triangle"
	| "lucide/align-end-horizontal"
	| "lucide/align-horizontal-distribute-end"
	| "radix/accessibility"
	| "radix/avatar"
	| "radix/bell"
	| "radix/camera"
	| "radix/card-stack"
	| "radix/pencil-1"
	| "radix/trash";
